// list of coffes
export default [
  {
    id: 1,
    name: "Health NGO",
    image: require("../../assets/coffees/health.jpg"),
    price: "2.00",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 1,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 2,
    name: "Health NGO2",
    image: require("../../assets/coffees/health1.jpg"),
    price: "4.01",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 1,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 3,
    name: "Education NGO",
    image: require("../../assets/coffees/education.jpg"),
    price: "3.05",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
        categoryId: 4,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 4,
    name: "Education NGO1",
    image: require("../../assets/coffees/education1.jpg"),
    price: "3.00",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 4,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 5,
    name: "Environment NGO",
    image: require("../../assets/coffees/environment.jpg"),
    price: "4.00",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 2,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 6,
    name: "Environment NGO2",
    image: require("../../assets/coffees/environment1.jpg"),
    price: "5.00",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 2,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 7,
    name: "Food NGO",
    image: require("../../assets/coffees/food.jpg"),
    price: "2.07",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 3,
    rating: 4.5,
    included: "With Gov.Body",
  },
  {
    id: 8,
    name: "Food NGO2",
    image: require("../../assets/coffees/food2.jpg"),
    price: "1.99",
    description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
    categoryId: 3,
    rating: 4.5,
    included: "With Gov.Body",
  },


// Reapeating same data
{
  id: 9,
  name: "Health NGO",
  image: require("../../assets/coffees/health.jpg"),
  price: "2.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 1,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 10,
  name: "Health NGO2",
  image: require("../../assets/coffees/health1.jpg"),
  price: "4.01",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 1,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 11,
  name: "Education NGO",
  image: require("../../assets/coffees/education.jpg"),
  price: "3.05",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
      categoryId: 4,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 12,
  name: "Education NGO1",
  image: require("../../assets/coffees/education1.jpg"),
  price: "3.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 4,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 13,
  name: "Environment NGO",
  image: require("../../assets/coffees/environment.jpg"),
  price: "4.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 2,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 14,
  name: "Environment NGO2",
  image: require("../../assets/coffees/environment1.jpg"),
  price: "5.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 2,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 15,
  name: "Food NGO",
  image: require("../../assets/coffees/food.jpg"),
  price: "2.07",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 3,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 16,
  name: "Food NGO2",
  image: require("../../assets/coffees/food2.jpg"),
  price: "1.99",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 3,
  rating: 4.5,
  included: "With Gov.Body",
},


{
  id: 17,
  name: "Health NGO",
  image: require("../../assets/coffees/health.jpg"),
  price: "2.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 1,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 18,
  name: "Health NGO2",
  image: require("../../assets/coffees/health1.jpg"),
  price: "4.01",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 1,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 19,
  name: "Education NGO",
  image: require("../../assets/coffees/education.jpg"),
  price: "3.05",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
      categoryId: 4,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 20,
  name: "Education NGO1",
  image: require("../../assets/coffees/education1.jpg"),
  price: "3.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 4,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 21,
  name: "Environment NGO",
  image: require("../../assets/coffees/environment.jpg"),
  price: "4.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 2,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 22,
  name: "Environment NGO2",
  image: require("../../assets/coffees/environment1.jpg"),
  price: "5.00",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 2,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 23,
  name: "Food NGO",
  image: require("../../assets/coffees/food.jpg"),
  price: "2.07",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 3,
  rating: 4.5,
  included: "With Gov.Body",
},
{
  id: 24,
  name: "Food NGO2",
  image: require("../../assets/coffees/food2.jpg"),
  price: "1.99",
  description:"A Health NGO is a non-profit organization focused on improving public health through initiatives like disease prevention, health education, and medical care access. These organizations work to support underserved communities by partnering with governments, international bodies, and other NGOs.",
  categoryId: 3,
  rating: 4.5,
  included: "With Gov.Body",
},

];
